spring:
  thymeleaf:
    mode: HTML
    check-template-location: on
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    #username: ${wichtel_db_user}
    #password: ${wichtel_db_passwort}
    #url: ${wichtel_db_url}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always
    hikari:
      maximum-pool-size: 5
    url: jdbc:postgresql://ec2-108-128-104-50.eu-west-1.compute.amazonaws.com:5432/dtmo7lcm15psu
    username: urrnvyxvpkrrjx
    password: 39025e8f19dcf63c857886edb8f08c096e7bd902dd1ead48cc040b275272a7d4

  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)
    open-in-view: false




