spring:
  thymeleaf:
    mode: HTML
    check-template-location: on
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    #username: ${wichtel_db_user}
    #password: ${wichtel_db_passwort}
    #url: ${wichtel_db_url}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always
    hikari:
      maximum-pool-size: 5
    url: jdbc:postgresql://ec2-54-72-155-238.eu-west-1.compute.amazonaws.com:5432/daigmif53si9l4
    username: pzxprjbsmpcwjf
    password: f7b41e11bd796da971e0aefd56de5f3c9bd253385d4d4596240ed279437a0a50

  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # (create, create-drop, validate, update)
    open-in-view: false




